### PR TITLE
Remove references to MiqPassword

### PR DESCRIPTION
**Pull request by Fryguy**
@carbonin Please review
cc @jrafanie

### CODE REVIEW

**Comment by carbonin** [comment]
Fine, I'll just close https://github.com/ManageIQ/manageiq-postgres_ha_admin/pull/13 then :trollface:

**Comment by Fryguy** [comment]
LOL oops

**Comment by Fryguy** [comment]
@carbonin Can you cut a version with this change?

**Comment by carbonin** [comment]
@Fryguy released version 3.0.1

**Pull request merged**
